name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: docker/build-push-action@v2.10.0
    - name: Login
      uses: docker/login-action@v1.14.1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Setup buildx
      uses: docker/setup-buildx-action@v1.7.0
    - name: Build and push
      uses: docker/build-push-action@v2.10.0
      with:
        content: .
        Dockerfile: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USER }}/ruby-asciidoctor-revealjs:latest
